
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aiproject-template
  title: aiproject Template
  description: Create a repo using aiproject template
  tags:
    - recommended
    - aiproject
spec:
  owner: mdtahseen.anam@hm.com
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - script: >-
        mkdir -p template
        cd template
        python3 -m venv .venv
        source .venv/bin/activate  
      displayName: install aiproject